version: '3.7'
services:
  fenice2.0-frontend:
    container_name: fenice2.0-frontend
    restart: always
    builds: ./client # change to image for prod
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_HOSTNAME=fenice2.0-backend
      - REACT_APP_BACKEND_PORT=4000
      - REACT_APP_PROD=true # set this for deployment
    links:
      - fenice2.0-backend
    depends_on: 
      - fenice2.0-backend
  fenice2.0-backend:
    container_name: fenice2.0-backend
    restart: always
    builds: ./server # change to image for prod
    ports:
        - "4000:4000"
    environment: 
      - REACT_APP_BACKEND_PORT=4000
networks:
  default:
    name: fenice2.0
