services:
  fenice2:
    container_name: fenice2
    restart: always
    build: . # change to image for prod
    # image: steeven9/fenice2
    platform: linux/amd64
    environment:
      # adjust if needed
      - MONGODB_URI=mongodb://user:password@mongodb:27017
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=supersecret
      - KEYCLOAK_ID=fenice2
      - KEYCLOAK_SECRET=testsecret
      - KEYCLOAK_ISSUER=https://my-keycloak-domain.com/realms/My_Realm
    ports:
      - "3000:3000"

  mongodb:
    container_name: mongodb
    restart: always
    image: bitnami/mongodb
    platform: linux/amd64
    environment:
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=password
      - MONGODB_ROOT_PASSWORD=password
      - MONGODB_DATABASE=fenice2
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

volumes:
  mongo:

networks:
  default:
    name: fenice2
