version: '3.9'
services:
  fenice2:
    container_name: fenice2
    restart: always
    build: . # change to image for prod
    environment:
      - MONGODB_URI=mongodb://user:password@mongodb:27017
    ports:
      - "3000:3000"

  mongodb:
    image: bitnami/mongodb
    container_name: mongodb
    environment:
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=password
      - MONGODB_ROOT_PASSWORD=password
      - MONGODB_DATABASE=dnd-alignment
    ports: 
      - 27017:27017
    volumes:
      - mongo:/data/db

volumes:
  mongo:
      
networks:
  default:
    name: fenice2
