name: Docker Image CI

# Build all branches
# Push only in main (:latest) and tags (:vX.Y.Z)

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"

jobs:
  build-and-push:
    uses: steeven9/CICD-template/.github/workflows/docker-build.yml@main
    with:
      image-name: steeven9/fenice2
      push: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
