name: Docker Image CI

# Build all branches and PRs
# Push only in main (:latest) and tags (:vX.Y.Z)

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  pull_request:
    branches:
      - github.event.repository.default_branch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/fenice2
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
      - name: Login to DockerHub
        if: github.event_name != 'pull_request' && github.ref_name == github.event.repository.default_branch
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: echo MONGODB_URI=${{ secrets.MONGODB_URI }} >> .env.local
      - name: Build and push
        uses: docker/build-push-action@v6.5.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' && github.ref_name == github.event.repository.default_branch }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
